### ISSUE TITLE
哥 附件在哪儿？

### ISSUE THREAD

**Issue by PettterWang** [CTF-Archives/2024-PandaCupCTF#1]

**Comment by Randark-JMT** [comment]
@ProbiusOfficial

**Comment by ProbiusOfficial** [comment]
别骂 等忙完

**Comment by 5ime** [comment]
忙完了吗🧐

> 别骂 等忙完

**Comment by Randark-JMT** [comment]
> 忙完了吗🧐
> 
> > 别骂 等忙完

支持正义谴责

![图片](https://github.com/user-attachments/assets/d106fb2e-d6f0-4eca-8e39-d29960b16232)

**Comment by shenghuo2** [comment]
> > 忙完了吗🧐
> > > 别骂 等忙完
> 
> 支持正义谴责
> 
> ![图片](https://private-user-images.githubusercontent.com/56223739/376240463-d106fb2e-d6f0-4eca-8e39-d29960b16232.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5MDk1NTYsIm5iZiI6MTcyODkwOTI1NiwicGF0aCI6Ii81NjIyMzczOS8zNzYyNDA0NjMtZDEwNmZiMmUtZDZmMC00ZWNhLThlMzktZDI5OTYwYjE2MjMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE0VDEyMzQxNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdiMWIwNWMxNzEwYmFiODM2N2IwZjMwMDI0NGFmNWM3MzFkODMxOGFjMjg0ZDM3MjUwZTJmYmIxMGZlOWYzOWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.a8zbKSo546q1vYVl-eC7MoRgKFgK_7OHf4aEFlTjkZI)

谴责喵

**Comment by Randark-JMT** [comment]
> _No description provided._

@PettterWang 附件已更新，请见Release
